apiVersion: funk.knative.dev/v1alpha1
kind: SDKInit
metadata:
  name: funk-go-sdk-deploy
spec:
  steps:
    - name: "Format go files"
      exec: "gofmt -l -w ./"
    - name: "Ensure dependencies"
      exec: "dep ensure"
    - name: "Build Functions and Deploy Functions/Triggers"
      exec: "ko apply -f config"
